### ISSUE TITLE
Add Il2CppApi.CreateDetour

### ISSUE THREAD

**Issue by Flowaria** [Kasuromi/GTFO-API#33]
https://github.com/Kasuromi/GTFO-API/blob/c70e583b6e22c21f610d0ea19779c745bdf25fb9/GTFO-API/Patches/GearManager_Patches.cs#L53-L72

Add Il2CppApi.CreateDetour api to support easier detour generation

**Comment by Kasuromi** [comment]
Added Il2CppAPI.CreateGenericDetour in 0.2.0
